baseurl = "https://astsu777.github.io"
title = "Astsu777 Blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

pagination.pagerSize = 20

[services]
# [services.disqus]
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Gaetan"
  info = "Security/Network Consultant"
  description = "My personal space"
  keywords = "blog,personal,security,cybersecurity,network,system,server"
  # avatarurl = "images/avatar.jpg"
  gravatar = "gaetan_934@yahoo.fr"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/astsu777/"
[[params.social]]
  name = "Reddit"
  icon = "fa-brands fa-reddit fa-2x"
  weight = 2
  url = "https://reddit.com/GSquad934"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/astsu777/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
